### ISSUE TITLE
Why is it not using unicode on Windows?

### ISSUE THREAD

**Issue by Yehouda** [scymtym/utilities.print-tree#1]
It has this line in print-tree.lisp
(defvar *use-unicode?* #-win32 t #+win32 nil)

Why?

It causes the test to fail, because the expected output is with unicode. 

Changing this to be T on windows too make it pass the test on Windows too (on LispWorks).

**Comment by scymtym** [comment]
When I tested this, I was using SBCL on Windows and Unicode did not work with the default settings at the time.

I have now asked people with access to SBCL on Windows to test whether it still does not work and will change the code accordingly (either to `#+(and win32 sbcl) nil` or just always `t`).
